function r_estimated = phasecoding(centers, accumMatrix, radiusRange)
%CHRADIIPHCODE Estimate circle radius for Circular Hough Transform using the Phase-Coding method
%   R_ESTIMATED = CHRADIIPHCODE(CENTERS, H, R) takes a two-column array CENTERS,
%   which contains the x (first column) and y (second column) coordinates
%   of the center locations, as input. It returns a vector R_ESTIMATED, which
%   contains the estimated radius value for each center and is the same
%   length as the number of rows in CENTERS. H is the complex accumulator
%   array (computed using CHACCUM) used for estimating the radius
%   values. If H is real, a warning is generated by the function and
%   the output radius vector R_ESTIMATED contains all zeros.


%% Check if accumulator array is complex
if (isreal(accumMatrix))
    warning(message('images:imfindcircles:realAccumArrayForPhaseCode'));
end

%% Decode the phase to get the radius estimate
cenPhase = angle(accumMatrix(sub2ind(size(accumMatrix),round(centers(:,2)),round(centers(:,1)))));
lnR = log(radiusRange);
r_estimated = exp(((cenPhase + pi)/(2*pi)*(lnR(end) - lnR(1))) + lnR(1)); % Inverse of modified form of Log-coding from Eqn. 8 in [1]

end
